import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'VQBox',
	description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <header className=''>
        </header>
        {/* このmainタグが各ページで内容がレンダリングされる */}
        <main>{children}</main>
        <footer className=''>
        </footer>
      </body>
    </html>
  );
}